import type { MarketplaceItem } from "@/components/item-card";

export const MOCK_LISTINGS: MarketplaceItem[] = [
  {
    id: "mock-vacuum",
    title: "Cordless Vacuum",
    description: "Works well on Harrington-style carpet. Empty the cup before you return it.",
    category: "Appliances",
    complex: "Laird Campus Suites",
    building: "George Read",
    status: "available",
    owner: { first_name: "Sam", last_name: "Miller" },
  },
  {
    id: "mock-steamer",
    title: "Garment Steamer",
    description: "Ready for Friday presentations. Distilled water only.",
    category: "Appliances",
    complex: "East Campus Traditional",
    building: "Caesar Rodney",
    status: "available",
    owner: { first_name: "Alex", last_name: "Nguyen" },
  },
  {
    id: "mock-grill",
    title: "George Foreman Grill",
    description: "Wipe the plates. No lingering fish smells, please.",
    category: "Kitchen",
    complex: "Laird Campus Suites",
    building: "Independence",
    status: "available",
    owner: { first_name: "Chris", last_name: "Patel" },
  },
  {
    id: "mock-drill",
    title: "Cordless Drill",
    description: "Two batteries. Please return both charged.",
    category: "Tools",
    complex: "Central/South Campus",
    building: "Ray Street A–B",
    status: "available",
    owner: { first_name: "Priya", last_name: "Shah" },
  },
  {
    id: "mock-dolly",
    title: "Moving Dolly / Hand Truck",
    description: "Folds flat for a closet. Use it for move-in boxes, then return it the same day.",
    category: "Tools",
    complex: "Laird Campus Suites",
    building: "James Smith",
    status: "available",
    owner: { first_name: "Jordan", last_name: "Lee" },
  },
  {
    id: "mock-pitcher",
    title: "Brita Filter Pitcher",
    description: "Fresh filter installed. Keep it in the fridge and swap it back before the weekend.",
    category: "Kitchen",
    complex: "Apartments",
    building: "University Courtyard",
    status: "available",
    owner: { first_name: "Maya", last_name: "Brooks" },
  },
];
